// Product data
export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: string;
  rating: number;
  reviewCount: number;
}

export const products: Product[] = [
  // Teas
  {
    id: '1',
    name: 'Organic Green Tea Premium',
    description: 'High-grade loose-leaf green tea from organic farms',
    price: 19.99,
    image: '/images/green-tea.jpg',
    category: 'Teas',
    rating: 4.9,
    reviewCount: 54,
  },
  {
    id: '2',
    name: 'White Tea Deluxe',
    description: 'Delicate white tea from premium estates',
    price: 24.99,
    image: '/images/white-tea.jpg',
    category: 'Teas',
    rating: 4.7,
    reviewCount: 32,
  },
  {
    id: '3',
    name: 'Herbal Blend Mix',
    description: 'Soothing blend with chamomile and lavender',
    price: 22.99,
    image: '/images/herbal-tea.jpg',
    category: 'Teas',
    rating: 4.8,
    reviewCount: 28,
  },
  {
    id: '4',
    name: 'Oolong Tea Collection',
    description: 'Traditional oolong from Taiwan',
    price: 26.99,
    image: '/images/oolong-tea.jpg',
    category: 'Teas',
    rating: 4.6,
    reviewCount: 41,
  },
  {
    id: '5',
    name: 'Puerh Tea Aged',
    description: 'Aged puerh tea for deep flavor',
    price: 34.99,
    image: '/images/puerh-tea.jpg',
    category: 'Teas',
    rating: 4.8,
    reviewCount: 19,
  },
  // Skincare
  {
    id: '6',
    name: 'Face Moisturizer',
    description: 'Organic face moisturizer for all skin types',
    price: 39.99,
    image: '/images/moisturizer.jpg',
    category: 'Skincare',
    rating: 4.6,
    reviewCount: 42,
  },
  {
    id: '7',
    name: 'Body Lotion',
    description: 'Nourishing body lotion with natural oils',
    price: 34.99,
    image: '/images/body-lotion.jpg',
    category: 'Skincare',
    rating: 4.5,
    reviewCount: 35,
  },
  {
    id: '8',
    name: 'Facial Serum',
    description: 'Anti-aging facial serum with vitamin C',
    price: 49.99,
    image: '/images/serum.jpg',
    category: 'Skincare',
    rating: 4.7,
    reviewCount: 28,
  },
  {
    id: '9',
    name: 'Face Cleanser',
    description: 'Gentle organic face cleanser',
    price: 29.99,
    image: '/images/cleanser.jpg',
    category: 'Skincare',
    rating: 4.7,
    reviewCount: 51,
  },
  {
    id: '10',
    name: 'Night Cream',
    description: 'Regenerating night cream for deep nourishment',
    price: 44.99,
    image: '/images/night-cream.jpg',
    category: 'Skincare',
    rating: 4.8,
    reviewCount: 36,
  },
  // Supplements
  {
    id: '11',
    name: 'Vitamin D3 Supplement',
    description: 'Organic vitamin D3 from plant-based source',
    price: 19.99,
    image: '/images/vitamin-d.jpg',
    category: 'Supplements',
    rating: 4.4,
    reviewCount: 21,
  },
  {
    id: '12',
    name: 'Omega-3 Fish Oil',
    description: 'Pure omega-3 fish oil supplement',
    price: 29.99,
    image: '/images/omega3.jpg',
    category: 'Supplements',
    rating: 4.6,
    reviewCount: 38,
  },
  {
    id: '13',
    name: 'Hemp Seed Oil',
    description: 'Cold-pressed, organic hemp seed oil',
    price: 34.99,
    image: '/images/hemp-oil.jpg',
    category: 'Supplements',
    rating: 4.7,
    reviewCount: 35,
  },
  {
    id: '14',
    name: 'Multivitamin Complex',
    description: 'Complete organic multivitamin formula',
    price: 39.99,
    image: '/images/multivitamin.jpg',
    category: 'Supplements',
    rating: 4.5,
    reviewCount: 29,
  },
  {
    id: '15',
    name: 'Probiotic Blend',
    description: 'Advanced probiotic for gut health',
    price: 44.99,
    image: '/images/probiotic.jpg',
    category: 'Supplements',
    rating: 4.8,
    reviewCount: 47,
  },
  // Hair Care
  {
    id: '16',
    name: 'Bamboo Hair Set',
    description: 'Sustainable bamboo hair care essentials',
    price: 29.99,
    image: '/images/bamboo-set.jpg',
    category: 'Hair Care',
    rating: 4.5,
    reviewCount: 18,
  },
  {
    id: '17',
    name: 'Shampoo Bar',
    description: 'Eco-friendly solid shampoo bar',
    price: 14.99,
    image: '/images/shampoo-bar.jpg',
    category: 'Hair Care',
    rating: 4.6,
    reviewCount: 33,
  },
  {
    id: '18',
    name: 'Conditioner Bar',
    description: 'Natural conditioner bar for all hair types',
    price: 14.99,
    image: '/images/conditioner-bar.jpg',
    category: 'Hair Care',
    rating: 4.5,
    reviewCount: 25,
  },
  {
    id: '19',
    name: 'Hair Oil Treatment',
    description: 'Nourishing hair oil with argan and jojoba',
    price: 24.99,
    image: '/images/hair-oil.jpg',
    category: 'Hair Care',
    rating: 4.7,
    reviewCount: 44,
  },
  // Wellness
  {
    id: '20',
    name: 'Yoga Mat Organic',
    description: 'Natural rubber yoga mat',
    price: 59.99,
    image: '/images/yoga-mat.jpg',
    category: 'Wellness',
    rating: 4.6,
    reviewCount: 22,
  },
  {
    id: '21',
    name: 'Meditation Cushion',
    description: 'Ergonomic meditation cushion',
    price: 49.99,
    image: '/images/meditation-cushion.jpg',
    category: 'Wellness',
    rating: 4.7,
    reviewCount: 18,
  },
  {
    id: '22',
    name: 'Aromatherapy Diffuser',
    description: 'Ultrasonic essential oil diffuser',
    price: 54.99,
    image: '/images/diffuser.jpg',
    category: 'Wellness',
    rating: 4.8,
    reviewCount: 39,
  },
];
